### ISSUE TITLE
Unable to resolve installation issues with pynini

### ISSUE THREAD

**Issue by alex13by** [AIFSH/ComfyUI-ChatTTS#2]
Under Windows 11, even with VisualStudio installed, errors are still encountered when compiling pynini:
Building wheels for collected packages: pynini
  Building wheel for pynini (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pynini (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pynini
      copying pynini\__init__.py -> build\lib.win-amd64-cpython-310\pynini
      creating build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\__init__.py -> build\lib.win-amd64-cpython-310\pywrapfst
      creating build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\case.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\chatspeak.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\chatspeak_model.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\dates.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\g2p.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\numbers.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\plurals.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\t9.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\weather.py -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\__init__.py -> build\lib.win-amd64-cpython-310\pynini\examples
      creating build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\export.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm_example.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\multi_grm.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\multi_grm_example.py -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\__init__.py -> build\lib.win-amd64-cpython-310\pynini\export
      creating build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\byte.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\edit_transducer.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\features.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\paradigms.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\pynutil.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\rewrite.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\rule_cascade.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\stringfile.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\tagger.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\utf8.py -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\__init__.py -> build\lib.win-amd64-cpython-310\pynini\lib
      running egg_info
      writing pynini.egg-info\PKG-INFO
      writing dependency_links to pynini.egg-info\dependency_links.txt
      writing top-level names to pynini.egg-info\top_level.txt
      reading manifest file 'pynini.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      writing manifest file 'pynini.egg-info\SOURCES.txt'
      copying pynini\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini
      copying pynini\__init__.pyi -> build\lib.win-amd64-cpython-310\pynini
      copying pynini\py.typed -> build\lib.win-amd64-cpython-310\pynini
      copying pywrapfst\BUILD.bazel -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\__init__.pyi -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pywrapfst\py.typed -> build\lib.win-amd64-cpython-310\pywrapfst
      copying pynini\examples\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\examples\py.typed -> build\lib.win-amd64-cpython-310\pynini\examples
      copying pynini\export\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\grm_py_build_defs.bzl -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\export\py.typed -> build\lib.win-amd64-cpython-310\pynini\export
      copying pynini\lib\BUILD.bazel -> build\lib.win-amd64-cpython-310\pynini\lib
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-310\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\extensions
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\AI\ComfyUI-aki-v1\python\include -ID:\AI\ComfyUI-aki-v1\python\Include /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-310\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl: 命令行 error D8021 :无效的数值参数“/Wno-register”
      error: command 'D:\\Program Files\\vs_BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
Failed to build pynini
ERROR: Could not build wheels for pynini, which is required to install pyproject.toml-based project

**Comment by AIFSH** [comment]
remove pynini from requirements and try install again

**Comment by AIFSH** [comment]
git pull
Windows disable text normalization now

**Comment by yiptsangkin** [comment]
same problem

**Comment by hymch** [comment]
same problem in different GUI

**Comment by Cupcc** [comment]
same problem in win10

**Comment by lord-lethris** [comment]
I think pynini wont install without VBS and the C++ library's installed.
I managed to get it to install a few months ago - but I think the latest's windows update has broke it.

**Comment by 3550292587** [comment]
> same problem in win10
如果是在windows中安装，我在这里找到了已经编译好的wheel，版本是2.6.1的
https://github.com/billwuhao/pynini-windows-wheels/releases/tag/v2.1.6.post1
下面的README.MD文件中有相关安装教程
https://github.com/billwuhao/ComfyUI_IndexTTS?tab=readme-ov-file
